app/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import login_user, logout_user, login_required, current_user

from app.models import Admin
from app.forms import LoginForm
from app.utils import redirect_back


auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('history.hello'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.filter_by(username=username).first()
        if admin:
            if admin.validate_password(password):
                login_user(admin, remember)
                flash('Welcome back.', 'info')
                return redirect_back()
            flash('Incorrect password.', 'warning')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect_back()

app/blueprints/member.py
from flask import Blueprint, render_template, request, jsonify
from app.models import User
from app.extensions import db
import requests
import os


member_count_per_page = int(os.getenv('member_count_per_page', '10'))
member_bp = Blueprint('member', __name__)


@member_bp.route('/list', methods=['GET'])
def list():
    '''
    This route will return the page contains the default paginate obj to show
    in page. and about the paginate obj refresh, we handle it by using Ajax.
    '''
    paginate = User.query.paginate(1, member_count_per_page, False)
    return render_template('member/member_list.html', paginate=paginate)


# the way to enable multiple route.
# @member_bp.route('/paginate', defaults={'page_num': 2}, methods=['GET'])
@member_bp.route('/paginate/<int:page_num>', methods=['GET'])
def paginate_obj(page_num):
    paginate = User.query.paginate(page_num, member_count_per_page, False)
    return render_template('member/member_table.html', paginate=paginate)


@member_bp.route('/delete/<uid>', methods=['GET', 'POST'])
def delete(uid):
    if request.method == 'POST':
        if not uid:
            return "Empty UID", 400
        User.query.filter_by(id=uid).delete()
        db.session.commit()
        return "Success", 200
    else:
        return "Not Support", 405


@member_bp.route('/update', methods=['GET', 'POST'])
def update():
    if request.method == 'POST':
        user = request.get_json()
        if not user['id']:
            return "Empty UID", 400
        tmp = User.query.filter_by(id=user['id'])[0]
        tmp.username = user['username']
        tmp.email = user['email']
        db.session.add(tmp)
        db.session.commit()
        response = jsonify(
            {"id": tmp.id, "username": tmp.username, "email": tmp.email})
        response.status_code = 200
        return response
    else:
        return "Not Support", 405


@member_bp.route('/add/<inumber>', methods=['GET'])
def add(inumber):
    inumber = inumber.upper()
    tmp = User.query.filter_by(id=inumber)
    if tmp.all():
        return "Duplicated", 400
    if not inumber:
        return "Invalid Inumber", 400
    tmp = User()
    tmp.id = inumber
    # fetch name and email from jira, finish later.
    jira_url = str(os.getenv('search_url')) + 'username=id'
    url = jira_url.replace('id', inumber)
    resp = requests.get(
        url, auth=(os.getenv('domainid'), os.getenv('domainpwd')))
    if resp.json():
        ret = resp.json()[0]
        tmp.username = ret['displayName']
        tmp.email = ret['emailAddress']
        db.session.add(tmp)
        db.session.commit()
        return "Success", 200
    else:
        return "No user with given i number found in Jira", 400

app/blueprints/provisioner.py
import os
import requests
from dotenv import load_dotenv
import logging

from flask import Blueprint, render_template, flash, redirect, url_for

from app.forms import RegisterProvisioner, MapCompany


provisioner_bp = Blueprint('provisioner', __name__)
load_dotenv()
domainurl = os.getenv('domainurl')
basic_token = os.getenv('rest_basic_token')

print('Properties: [%s, %s]' % (domainurl, basic_token))


def get_access_token():
    # get rest API token
    payload = '{"grant_type":"client_credentials",\
        "scope":"userId=SFV4,resourceType=sfprovisioning"}'
    url = "%s/api/oauth/rest/v1/token" % domainurl
    headers = {
        'Content-type': "application/json",
        'Authorization': basic_token}

    response = requests.request("POST", url, data=payload, headers=headers)
    logging.warning("Get token status: %s" % response.status_code)

    json_ret = response.json()
    return "%s %s" % (json_ret['token_type'], json_ret['access_token'])


@provisioner_bp.route('/register', methods=['GET', 'POST'])
def register_provisioner():
    form = RegisterProvisioner()
    if form.validate_on_submit():
        inumber = form.inumber.data
        email = form.email.data

        # send request to create provisioner
        prov_header = {
            'Content-type': "application/json",
            'Authorization': get_access_token()
        }

        prov_payload = '{"provisionerId": "%s",\
            "provisionerName":"%s","provisionerPassword":"pwd",\
                "provisionerEmail":"%s"}' % (inumber, inumber, email)

        prov_url = "%s/provisioningapi/provisioning/dataservice"\
            "/rest/v1/createprovisioner" % domainurl

        resp = requests.request(
            "POST", prov_url, data=prov_payload, headers=prov_header)
        logging.warning("Create provisioner status: %s" % resp.status_code)

        # permission flag: 16777218, edit company + disable popup
        permission_payload = '{"provisionerId":"%s",\
            "provisionerFlag":"16777234"}' % inumber
        permission_url = "%s/provisioningapi/provisioning/dataservice"\
            "/rest/v1/setprovisionerperm" % domainurl
        resp = requests.request(
            "POST", permission_url, data=permission_payload,
            headers=prov_header)
        logging.warning("Assign permission status: %s" % resp.status_code)

        flash('Provisioner account has been created. \
            please clean browser cache and re-login.', 'success')
        return redirect(url_for('.map_company', inumber=inumber))
    return render_template('provisioner/register_provisioner.html', form=form)


@provisioner_bp.route(
    '/map-company', defaults={'inumber': ''}, methods=['GET', 'POST'])
@provisioner_bp.route('/map-company/<inumber>', methods=['GET', 'POST'])
def map_company(inumber):
    form = MapCompany()
    form.inumber.data = inumber
    if form.validate_on_submit():
        id = form.inumber.data
        cid = form.company.data

        # send request to map provisioner to company
        headers = {
            'Content-type': "application/json",
            'Authorization': get_access_token()
        }
        url = "%s/provisioningapi/provisioning/dataservice/"\
            "rest/v1/mapprovisionertocompany" % domainurl
        payload = '{"provisionerId" : "%s","companyId": "%s"}' % (id, cid)
        resp = requests.request("POST", url, data=payload, headers=headers)
        if resp.status_code == 200:
            flash(
                'Company: %s has mapped to provisioner: %s' % (id, cid),
                'success')
        else:
            flash('Map failed, error %s' % resp.text, 'danger')
        return redirect(url_for('.map_company'))
    return render_template('/provisioner/map_company.html', form=form)

app/templates/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
    {%- block html %}

    <head>
        {%- block head %}
        <title>{% block title %}{{title|default}}{% endblock title %}</title>

        {%- block metas %}
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {%- endblock metas %}

        {%- block styles %}
        <!-- Bootstrap -->
        <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}" type="text/css">
        <!--link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css"-->
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {%- endblock styles %}
        {%- endblock head %}
    </head>

    <body{% block body_attribs %}{% endblock body_attribs %}>
        {% block body -%}
        {% block navbar %}
        <div class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Analyser</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Provisioner
                            </a>
                            <div class="dropdown-menu pull-left">
                                <a class="dropdown-item" href="{{ url_for('provisioner.register_provisioner') }}">Register Provisioner</a><br>
                                <a class="dropdown-item" href="{{ url_for('provisioner.map_company') }}">Map To Company</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                GoTo
                            </a>
                            <div class="dropdown-menu pull-left">
                                <a class="dropdown-item" href="{{ url_for('member.list') }}">Member List</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout', next=request.full_path) }}">Logout</a>
                            {% else %}
                            <a href="{{ url_for('auth.login', next=request.full_path) }}">Login</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endblock navbar %}

        <div class="container">
            {% for category, message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ category }}" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <div class="container">
                {% block content %}{% endblock content %}
            </div>
        </div>

        {% block footer %}
        <footer class="footer navbar-fixed-bottom">
            <div class="container">
                <p class="text-muted text-center">
                    <small>
                        &copy; 2019 - Jack is working on this site contribution.
                    </small>
                </p>
            </div>

        </footer>
        {% endblock %}

        {% block scripts %}
        <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
        <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
        {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
        
        {#{ moment.locale('zh-cn') }#}
        {% endblock %}
        {%- endblock body %}
        </body>
        {%- endblock html %}

        </html>
        {% endblock doc -%}